CXX = g++
CXXFLAGS = -Wall -Wextra -std=c++17
TARGET = chess
SOURCES = main.cpp board.cpp
OBJECTS = $(SOURCES:.cpp=.o)

all: $(TARGET)

$(TARGET): $(OBJECTS)
    $(CXX) $(CXXFLAGS) -lfmt -o $(TARGET) $(OBJECTS)

%.o: %.cpp
    $(CXX) $(CXXFLAGS) -c $<

clean:
    rm -f $(OBJECTS) $(TARGET)

.PHONY: all clean